version: '3.6'

services:
  base:
    container_name: gambot_gateway
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
      - '.:/src'
    ports:
      - 5004:5000
    environment:
      - FLASK_APP=project/__init__.py
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - GAMBOT_CARD_URL=http://gambot_card:5000/
      - GAMBOT_GAME_URL=http://gambot_game:5000/
      - GAMBOT_PLAYER_URL=http://gambot_players:5000/
    networks:
      - gambotnetwork

networks:
  gambotnetwork:
    driver: "bridge"
    name: gambotnetwork